version: '3.5'

services:
  my-lab:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/mylab
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth
      - KEYCLOAK_REALM=master
      - KEYCLOAK_CLIENT_ID=mylab
      - KEYCLOAK_CLIENT_SECRET=09a71c59-0351-4ce6-bc8f-8fd3feb9d2ff
    depends_on:
      - mongodb
      - keycloak
    restart: always
    volumes:
      - ./:/app
    networks:
      - my-lab-network

  keycloak:
    image: jboss/keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    restart: always
    depends_on:
      - mongodb
    networks:
      - my-lab-network

  mongodb:
    image: mongo:4.4
    environment:
      MONGO_INITDB_DATABASE: mylab
    ports:
      - "27018:27017"
    restart: always
    volumes:
      - db-data:/var/lib/mongo/data
    networks:
      - my-lab-network

volumes:
  db-data:

networks:
  my-lab-network:
    driver: bridge